# Generated by Django 3.2.5 on 2021-12-22 17:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('S_ID', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='Invalid', message='Invalid', regex='^1VE\\d\\d\\w\\w\\d\\d\\d')])),
                ('S_NAME', models.CharField(max_length=30)),
                ('S_DOB', models.DateField()),
                ('S_SEM', models.IntegerField()),
                ('S_SEC', models.CharField(max_length=1)),
                ('S_DEP', models.CharField(max_length=3)),
                ('S_PIC', models.ImageField(blank=True, upload_to='capp/profile_pic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnionForm',
            fields=[
                ('UNION_ID', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('UNION_NAME', models.CharField(max_length=25)),
                ('M1', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='Invalid', message='Invalid', regex='^1VE\\d\\d\\w\\w\\d\\d\\d')])),
                ('M2', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='Invalid', message='Invalid', regex='^1VE\\d\\d\\w\\w\\d\\d\\d')])),
                ('M3', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='Invalid', message='Invalid', regex='^1VE\\d\\d\\w\\w\\d\\d\\d')])),
                ('M4', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='Invalid', message='Invalid', regex='^1VE\\d\\d\\w\\w\\d\\d\\d')])),
                ('M5', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='Invalid', message='Invalid', regex='^1VE\\d\\d\\w\\w\\d\\d\\d')])),
                ('head', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='capp.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Union',
            fields=[
                ('UNION_ID', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('UNION_NAME', models.CharField(max_length=25)),
                ('head', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='capp.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USN', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='capp.studentprofile')),
                ('U_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='capp.union')),
            ],
        ),
    ]
