# Generated by Django 3.2.5 on 2021-12-28 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0003_auto_20211223_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('U_NAME', models.CharField(max_length=25)),
                ('V_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='capp.studentprofile')),
            ],
        ),
    ]
